@startuml
!include style.puml

participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant ":XYZ Predicate" as Predicate LOGIC_COLOR

mainframe sd get predicates
    activate FindCommandParser
    create Predicate
    FindCommandParser -> Predicate
    note right
        Refers to any predicate with the corresponding prefix found in the ArgumentMultimap
        For example, n/ in the command will give a NameContainsKeywordPredicate
    end note
    activate Predicate

    Predicate --> FindCommandParser
    deactivate Predicate

    FindCommandParser -> FindCommandParser : add(XYZ Predicate)
    activate FindCommandParser
    FindCommandParser --> FindCommandParser
    deactivate FindCommandParser

@enduml
